export const langs = {
  "backup": {
    "backup": "Copia de seguridad",
    "create_a_new_backup": "Crear una copia de seguridad",
    "existing_backups": "Copias de seguridad existentes",
    "date": "Fecha",
    "file_size": "Tamaño del fichero",
    "actions": "Acciones",
    "download": "Descargar",
    "delete": "Eliminar",
    "delete_confirm": "¿Estás seguro que quieres borrar esta copia de seguridad?",
    "delete_confirmation_title": "Confirmado",
    "delete_confirmation_message": "La copia de seguridad fue eliminada.",
    "delete_error_title": "Ups, ha ocurrido un error",
    "delete_error_message": "La copia de seguridad NO se pudo eliminar.",
    "delete_cancel_title": "La operación ha sido cancelada",
    "delete_cancel_message": "La copia de seguridad NO se pudo eliminar.",
    "create_confirmation_title": "Se ha completado la copia de seguridad",
    "create_confirmation_message": "Recargando la página en 3 segundos.",
    "create_error_title": "Error al realizar la copia de seguridad",
    "create_error_message": "La copia de seguridad NO se pudo crear.",
    "create_warning_title": "Estamos presentando problemas",
    "create_warning_message": "La copia de seguridad puede que no se haya realizado. Por favor verifica los logs para más detalles.",
    "location": "Ubicación",
    "no_disks_configured": "No existe ningún disco configurado config/laravel-backup.php",
    "backup_doesnt_exist": "La copia de seguridad no existe.",
    "only_local_downloads_supported": "Solo se permiten descargas del sistema de archivos local."
  },
  "base": {
    "registration_closed": "El registro de usuarios está cerrado.",
    "first_page_you_see": "La página que ves después de iniciar sesión",
    "login_status": "Estado de la conexión",
    "logged_in": "¡Usted ha iniciado sesión!",
    "toggle_navigation": "Activar/desactivar la navegación",
    "administration": "ADMINISTRACIÓN",
    "user": "USUARIO",
    "logout": "Salir",
    "login": "Iniciar sesión",
    "register": "Crear usuario",
    "name": "Nombre",
    "email_address": "Correo",
    "password": "Contraseña",
    "confirm_password": "Confirmar contraseña",
    "remember_me": "Recordar contraseña",
    "forgot_your_password": "¿Olvidó su contraseña?",
    "reset_password": "Restaurar contraseña",
    "send_reset_link": "Enviar enlace para restaurar la contraseña",
    "click_here_to_reset": "Click aquí para restaurar la contraseña",
    "unauthorized": "No autorizado.",
    "dashboard": "Panel",
    "handcrafted_by": "Realizado por",
    "powered_by": "Creado con",
    "file_manager": "Administrador de Archivos"
  },
  "crud": {
    "save_action_save_and_new": "Guardar y crear nuevo",
    "save_action_save_and_edit": "Guardar y continuar editando",
    "save_action_save_and_back": "Guardar y regresar",
    "save_action_changed_notification": "La acción por defecto del botón guardar ha sido modificada.",
    "add": "Añadir",
    "back_to_all": "Volver al listado de",
    "cancel": "Cancelar",
    "add_a_new": "Añadir ",
    "back": "Atras",
    "proccess": "Procesar",
    "edit": "Editar",
    "save": "Guardar",
    "apply": "Aplicar",
    "select": "Seleccionar",
    "reject": "Rechazar",
    "revisions": "revisiones",
    "no_revisions": "No hay revisiones encontradas",
    "created_this": "creado este",
    "changed_the": "cambiado el",
    "restore_this_value": "restaurar este valor",
    "from": "de",
    "to": "a",
    "undo": "Deshacer",
    "revision_restored": "Revisión restaurada correctamente",
    "all": "Todos los registros de ",
    "in_the_database": "en la base de datos",
    "list": "Listar",
    "actions": "Acciones",
    "preview": "Vista previa",
    "delete": "Eliminar",
    "admin": "Admin",
    "details_row": "Esta es la fila de detalles. Modificar a su gusto.",
    "details_row_loading_error": "Se ha producido un error al cargar los datos. Por favor, intente de nuevo.",
    "delete_confirm": "¿Está seguro que desea eliminar este elemento?",
    "delete_confirmation_title": "Elemento eliminado",
    "delete_confirmation_message": "El elemento ha sido eliminado de manera correcta.",
    "delete_confirmation_not_title": "No se pudo eliminar",
    "delete_confirmation_not_message": "Ha ocurrido un error. Puede que el elemento no haya sido eliminado.",
    "delete_confirmation_not_deleted_title": "No se pudo eliminar",
    "delete_confirmation_not_deleted_message": "No ha ocurrido nada. Su elemento está seguro.",
    "emptyTable": "No hay datos disponibles en la tabla",
    "info": "Mostrando registros _START_ a _END_ de un total de _TOTAL_ registros",
    "infoEmpty": "Mostrando 0 registros",
    "infoFiltered": "(filtrando de _MAX_ registros totales)",
    "infoPostFix": "",
    "thousands": ",",
    "lengthMenu": "_MENU_ elementos por página",
    "loadingRecords": "Cargando...",
    "processing": "Procesando...",
    "search": "Buscar: ",
    "zeroRecords": "No se encontraron elementos",
    "paginate": {
      "first": "Primero",
      "last": "Último",
      "next": "Siguiente",
      "previous": "Anterior"
    },
    "export": {
      "copy": "Copiar",
      "excel": "Excel",
      "csv": "Csv",
      "pdf": "Pdf",
      "print": "Imprimir",
      "column_visibility": "Columnas"
    },
    "aria": {
      "sortAscending": ": activar para ordenar ascendentemente",
      "sortDescending": ": activar para ordenar descendentemente"
    },
    "unauthorized_access": "Acceso denegado - usted no tiene los permisos necesarios para ver esta página.",
    "please_fix": "Por favor corrija los siguientes errores:",
    "insert_success": "El elemento ha sido añadido de manera correcta.",
    "update_success": "El elemento ha sido modificado de manera correcta.",
    "reorder": "Reordenar",
    "reorder_text": "Arrastrar y soltar para reordenar.",
    "reorder_success_title": "Hecho",
    "reorder_success_message": "El orden ha sido guardado.",
    "reorder_error_title": "Error",
    "reorder_error_message": "El orden no se ha guardado.",
    "yes": "Sí",
    "no": "No",
    "upload": "Subir",
    "browse_uploads": "Subir archivos",
    "close": "Cerrar",
    "clear": "Limpiar",
    "filter": "Filtro",
    "filters": "Filtros",
    "remove filters": "Remover Filtros",
    "page_link": "Enlace",
    "page_link_placeholder": "http://example.com/su-pagina",
    "internal_link": "Enlace interno",
    "internal_link_placeholder": "Slug interno. Ejplo: 'admin/page' (sin comillas) para ':url'",
    "external_link": "Enlace externo",
    "file_manager": "Administrador de Archivos",
    "created": "creado",
    "updated": "actualizado",
    "deleted": "borrado",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Last 7 Days": "Ultimos 7 Dias",
    "Last 30 Days": "Ultimos 30 Dias",
    "This Month": "Este Mes",
    "Last Month": "Ultimo Mes"
  },
  "date": {
    "date": "Fecha",
    "day": "Día",
    "days": "Dias",
    "month": "Mes",
    "year": "Año",
    "from": "Del",
    "to": "Hasta",
    "hour": "Hora",
    "minute": "Minuto",
    "monday": "Lunes",
    "tuesday": "Martes",
    "wednesday": "Miercoles",
    "thursday": "Jueves",
    "friday": "Viernes",
    "saturday": "Sabado",
    "sunday": "Domingo",
    "date range": "Rango de Fechas",
    "second": "Segundo",
    "day name": "Nombre del Día",
    "month name": "Nombre del mes",
    "next": "Próximo",
    "tomorrow": "Mañana",
    "today": "Hoy",
    "yesterday": "Ayer",
    "week": "Esta Semana",
    "this_week": "Esta Semana",
    "last_week": "Semana Pasada",
    "this_month": "Este Mes",
    "last_month": "Mes Pasado",
    "this_year": "Este Año",
    "last_year": "El Año Pasado",
    "older": "Antiguos"
  },
  "emails": {
    "hello": "Hola :Name",
    "invoice_paid": "Una de tus :invoices ha sido pagada! ",
    "new_invoice": "Tienes una nueva :invoice",
    "footer": "Gracias por usar Residencias Online",
    "regards": "Saludos"
  },
  "finances": {
    "payment_received": ":payment recibido",
    "payment_accepted": ":payment aceptado",
    "payment_rejected": ":payment rechazado"
  },
  "langfilemanager": {
    "active": "Activo",
    "cant_edit_online": "Este Idioma no puede ser editado online.",
    "code_iso639-1": "Codido (ISO 639-1)",
    "default": "Defecto",
    "empty_file": "No hay traducciones disponibles.",
    "flag_image": "imagen Bandera",
    "key": "Key",
    "language": "lenguaje",
    "language_name": "Nombre del Lenguaje",
    "language_text": "texto en  :language_name",
    "language_translation": "traducción en :language_name",
    "languages": "Lenguajes",
    "please_fill_all_fields": "Por favor, rellene todos los campos",
    "rules_text": "<strong>Nota: </strong> Do not translate words prefixed with colon (ex: ':number_of_items'). Those will be replaced automatically with a proper value. If translated, that stops working.",
    "saved": "Guardado",
    "site_texts": "Textos del sitio",
    "switch_to": "Cambiar a",
    "texts": "Textos",
    "translate": "Traddución",
    "translations": "Tradduciones",
    "native_name": "Nombre nativo"
  },
  "literals": {
    "opened_at": "Abierta el",
    "open": "Abierto",
    "opens": "Abiertos",
    "actions": "Acciones",
    "action": "Acción",
    "about": "Acerca",
    "is active": "Esta Activo",
    "active": "Activo",
    "actives": "Activos",
    "inactive": "Inactivo",
    "inactives": "Inactivos",
    "notification": "Notificación",
    "notifications": "Notificaciones",
    "authorization": "Autorización",
    "authorizations": "Autorizaciones",
    "update": "Actualizar",
    "aditional": "Adicional",
    "additional": "Adicional",
    "administration": "Administración",
    "administrator": "Administrador",
    "add": "Agregar",
    "solvents": "Al día",
    "solvent": "Al día",
    "ambulance": "Ambulancia",
    "apartment": "Apartamento",
    "last_name": "Apellidos",
    "approved_f": "Aprobada",
    "approveds_f": "Aprobadas",
    "approved": "Aprobado",
    "approveds": "Aprobados",
    "file": "Archivo",
    "files": "Archivos",
    "zone": "Area",
    "zones": "Areas",
    "subject": "Asunto",
    "audit": "Auditoria",
    "audits": "Auditorias",
    "advanced": "Avanzado",
    "banner": "Banner",
    "banners": "Banners",
    "bus": "Bus",
    "search": "Buscar",
    "every": "Cada",
    "van": "Camioneta",
    "field": "Campo",
    "fields": "Campos",
    "extras": "Campos Adicionales",
    "cancelled": "Anulado",
    "canceled_at": "Anulado el",
    "cancelleds": "Anulados",
    "quantity": "Cantidad",
    "characteristics": "Caracteristicas",
    "charge": "Cargo",
    "charges": "Cargos",
    "car": "Carro",
    "golf_cart": "Carro de golf",
    "house": "Casa",
    "category": "Categoria",
    "categories": "Categorias",
    "document": "Cedula",
    "closed_at": "Cerrada el",
    "closed": "Cerrado",
    "closeds": "Cerrados",
    "in proccess": "En proceso",
    "logout": "Cerrar Sesión",
    "check": "Cheque",
    "cash_desk": "Cierre de Caja",
    "cash_desks": "Cierre de Cajas",
    "customer": "Cliente",
    "customers": "Clientes",
    "alicuota": "Coeficiente",
    "color": "Color",
    "comunity": "Comunidad",
    "comunities": "Comunidades",
    "in_discount": "Con Descuento",
    "in_interest": "Con Intereses de mora",
    "concept": "Concepto",
    "owner": "Propietario",
    "owners": "Propietarios",
    "settings": "Configuración",
    "confirm": "Confirmar",
    "password_confirmation": "Confirmar Contraseña",
    "emergency_contact": "Contacto de Emergencia",
    "content": "Contenido",
    "password": "Contraseña",
    "spouse": "Conyuge",
    "correspondence": "Correspondencia",
    "correspondences": "Correspondencias",
    "creator": "Creador",
    "creators": "Creadores",
    "payable_account": "Cuenta por Cobrar",
    "payable_accounts": "Cuentas por Cobrar",
    "quota": "Cuota",
    "quotas": "Cuotas",
    "deposit": "Deposito",
    "download": "Descargar",
    "description": "Descripción",
    "featured": "Destacado",
    "show_feature": "Destacar en el catalogo",
    "detailed": "Detallado",
    "details": "Detalles",
    "debt": "Deuda",
    "debts": "Deudas",
    "dynamic": "Dinamico",
    "address": "Dirección",
    "directives": "Directiva",
    "directive": "Directivo",
    "available": "Disponible",
    "available_for_defaulter": "Disponible para moroso",
    "availables": "Disponibles",
    "dynamic_document": "Documento",
    "dynamic_documents": "Documentos",
    "delivery": "Domicilio",
    "deliveries": "Domicilios",
    "cash": "Efectivo",
    "example": "Ejemplo",
    "delete": "Eliminar",
    "email": "Email",
    "comunity_email": "Email",
    "in_proccess": "En Proceso",
    "survey": "Encuesta",
    "surveys": "Encuestas",
    "login": "Entrar",
    "login_with_Facebook": "Entrar Con Facebook",
    "login_with_Google": "Entrar Con Google",
    "delivered": "Entregado",
    "delivered_at": "Entregado el",
    "delivered at": "Entregado el",
    "departured_at": "Ido a las",
    "departured at": "Ido a las",
    "start_at": "Comienza el",
    "start at": "Comienza el",
    "end_at": "Termina el",
    "end at": "Termina el",
    "authorized by": "autorizado por",
    "sent": "Enviado",
    "send": "Enviar",
    "choose": "Escoger",
    "choose_file": "Escoger Archivo",
    "special": "Especial",
    "specie": "Especie",
    "warehouse": "Almacén",
    "warehouses": "Almacenes",
    "waiting_for_confirmation": "Esperando Confirmación",
    "waiting for confirmation": "Esperando Confirmación",
    "waiting_for_approval": "Esperando por Aprobación",
    "waiting for approval": "Esperando por Aprobación",
    "status": "Estado",
    "marital_status": "Estado Civil",
    "tag": "Etiqueta",
    "tags": "Etiquetas",
    "event": "Evento",
    "events": "Eventos",
    "export": "Exportar",
    "invoice": "Factura",
    "invoice_number": "Factura #",
    "invoices": "Facturas",
    "faileds": "Fallidos",
    "date": "Fecha",
    "birthday": "Fecha de Nacimiento",
    "dates": "Fechas",
    "sex_femenine": "Femenino",
    "end_date": "Fin",
    "finances": "Finanzas",
    "signature": "Firma",
    "signatures": "Firmas",
    "winner": "Ganador",
    "expense": "Gasto",
    "expenses": "Gastos",
    "generate": "Generar",
    "free": "Gratis",
    "group": "Grupo",
    "groups": "Grupos de Residencias",
    "brother": "Hermano",
    "son": "Hijo",
    "panic_logs": "Historial de Emergencias",
    "male": "Hombre",
    "schedule": "Horario",
    "schedules": "Horarios",
    "id": "ID",
    "ids": "Ids",
    "image": "Imagen",
    "images": "Imagenes",
    "import": "Importar",
    "print": "Imprimir",
    "tax": "Impuesto",
    "taxes": "Impuestos",
    "start_date": "Inicio",
    "boat": "Lancha",
    "language": "Lenguaje",
    "languages": "Lenguajes",
    "url": "Link",
    "list": "Lista",
    "lists": "Listas",
    "done": "Listo",
    "arrive": "Llegada",
    "local": "Local",
    "locals": "Locales",
    "lot": "Lote",
    "place": "Lugar",
    "places": "Lugares",
    "limit_user": "Límite de usuarios",
    "limit user": "Límite de usuarios",
    "model": "Línea",
    "make": "Marca",
    "mark_as": "Marcar como",
    "pet": "Mascota",
    "pets": "Mascotas",
    "sex_masculine": "Masculino",
    "amount": "Monto",
    "show_price": "Mostrar el precio en el catalogo",
    "show_stock": "Mostrar el stock en el catalogo",
    "bike": "Moto",
    "female": "Mujer",
    "method": "Método",
    "methods": "Métodos",
    "comunity_document": "NIT",
    "no": "No",
    "undefined": "No Definido",
    "no_generated": "No Generado",
    "unpaid": "No Pagado",
    "name": "Nombre",
    "first_name": "Nombres",
    "note": "Nota",
    "notes": "Notas",
    "post": "Noticia",
    "posts": "Noticias",
    "number_of_people": "Numero de personas",
    "never_reclaimed": "Nunca Reclamado",
    "number": "Número",
    "phone_number": "Número de Telefono",
    "numbers": "Números",
    "occuped": "Ocupado",
    "other": "Otro",
    "tickets": "PQRs",
    "parent": "Padre",
    "parent category": "Categoría Padre",
    "parent categories": "Categorias Padre",
    "paid": "Pagado",
    "paid_at": "Pagado el",
    "page": "Pagina",
    "pages": "Paginas",
    "payment": "Pago",
    "payments": "Pagos",
    "panic": "Emergencia",
    "panics": "Emergencias",
    "to": "Para",
    "lobby": "Control de Acceso",
    "parameter": "Parametro",
    "parameters": "Parametros",
    "partially_paid": "Parcialmente Pagado",
    "partially paid": "Parcialmente Pagado",
    "relationship": "Parentesco",
    "relationship_large": "Parentesco con el propietario",
    "parking": "Parqueadero",
    "parkings": "Parqueaderos",
    "pending": "Pendiente",
    "pendings": "Pendientes",
    "lost": "Perdido",
    "permission": "Permiso",
    "permissions": "Permisos",
    "person": "Persona",
    "persons": "Personas",
    "plate": "Placa",
    "percent": "Porcentaje",
    "slider": "Portada",
    "sliders": "Portadas",
    "price": "Precio",
    "residence": "Vivienda",
    "residences": "Viviendas",
    "question": "Pregunta",
    "privacity": "Privacidad",
    "product": "Producto",
    "products": "Productos",
    "breed": "Raza",
    "reason": "Razón",
    "receptor": "Receptor",
    "receptors": "Receptores",
    "rejected_f": "Rechazada",
    "rejecteds_f": "Rechazadas",
    "rejected": "Rechazado",
    "rejecteds": "Rechazados",
    "reject": "Rechazar",
    "receipt": "Recibo",
    "receipts": "Recibos",
    "reference": "Referencia",
    "references": "Referencias",
    "sign_in": "Registrarse",
    "rent": "Arriendo",
    "report": "Reporte",
    "reports": "Reportes",
    "reservations": "Reservaciones",
    "reservation": "Reservación",
    "server": "Servidor",
    "servers": "Servidores",
    "home": "Inicio",
    "reserved": "Reservado",
    "reservate": "Reservar",
    "backup": "Respaldos",
    "backups": "Respaldo",
    "answer": "Respuesta",
    "resume_charges": "Resumen de Gastos",
    "role": "Rol",
    "roles": "Roles",
    "roles_have_permission": "Roles que tienen permiso",
    "user_role_permission": "Roles y Permisos",
    "comment": "Seguimiento",
    "comments": "Seguimientos",
    "select": "Seleccionar",
    "select_:person": "Seleccionar Persona",
    "sex": "Sexo",
    "yes": "Si",
    "solvency": "Solvencia",
    "solvencys": "Solvencias",
    "stock": "Stock",
    "subtotal": "Subtotal",
    "size": "Tamano",
    "credit card": "Tarjeta de Crédito",
    "credit_card": "Tarjeta de Crédito",
    "debit card": "Tarjeta de Debito",
    "debit_card": "Tarjeta de Debito",
    "comunity_phone": "Telefono",
    "phone": "Teléfono",
    "text": "Texto",
    "time": "Tiempo",
    "close_time": "Tiempo de cierre",
    "type": "Tipo",
    "title": "Titulo",
    "all(f)": "Todas",
    "all_day": "Todo el Día",
    "all": "Todos",
    "total": "Total",
    "worker": "Trabajador",
    "workers": "Trabajadores",
    "work": "Trabajo",
    "translates": "Traducciones",
    "translate": "Traducción",
    "transactions": "Transaciones",
    "transaction": "Transación",
    "transfer": "Transferencia",
    "location": "Ubicación",
    "user": "Usuario",
    "users": "Usuarios",
    "value": "Valor",
    "neighbor": "Vecino",
    "neighbors": "Vecinos",
    "vehicle": "Vehiculo",
    "vehicles": "Vehiculos",
    "seller": "Vendedor",
    "sellers": "Vendedores",
    "sync": "Sincronizar",
    "observations": "Observaciones",
    "with": "Con",
    "without": "Sin",
    "having": "Teniendo",
    "sell_without_stock": "Vendible sin Stock",
    "view_resource": "Ver",
    "visibility": "Visibilidad",
    "visit": "Visita",
    "visits": "Visitas",
    "special_visit": "Visita Especial",
    "visitor": "Visitante",
    "visitors": "Visitantes",
    "unkown_visitor": "Visitante Desconocido",
    "preview": "Vista Previa",
    "fingerprint sensor": "Lector de huellas",
    "fingerprint": "Huella Dactilar",
    "fingerprints": "Huellas",
    "votes": "Votos",
    "admin": "admin",
    "bicycle": "bicicleta",
    "end": "fin",
    "cat": "gatos",
    "departured": "ido",
    "start": "inicio",
    "interval": "intervalo",
    "duration": "Duración",
    "item": "item",
    "items": "items",
    "arrival": "llegada",
    "logs": "logs",
    "my": "mi",
    "my_vote": "mi voto",
    "defaulter": "moroso",
    "defaulters": "morosos",
    "more": "más",
    "none": "ninguno",
    "normal": "normal",
    "profile": "perfil",
    "dog": "perro",
    "personal": "personal",
    "reservable": "reservable",
    "residential": "residencial",
    "ticket": "ticket",
    "your_vote": "tu voto",
    "vote": "voto"
  },
  "logmanager": {
    "log_manager": "Log Manager",
    "log_manager_description": "Ver, descargar y eliminar logs.",
    "actions": "Acciones",
    "delete_confirm": "Estas seguro de que quieres eliminar este archivo de log?",
    "back_to_all_logs": "Volver a los logs",
    "create_a_new_log": "Crear nuevo log",
    "date": "Fecha",
    "delete": "Eliminar",
    "delete_confirmation_title": "Hecho",
    "download": "Descargar",
    "delete_error_title": "Error",
    "existing_logs": "Logs Existentes",
    "file_size": "Tamano del archivo",
    "delete_cancel_title": "It&#039;s ok",
    "last_modified": "Ultima Modificacion",
    "logs": "Logs",
    "preview": "Ver",
    "delete_cancel_message": "El log no ha sido borrado",
    "delete_error_message": "El log no ha sido borrado",
    "delete_confirmation_message": "El log fue borrado existosamente",
    "log_file_doesnt_exist": "El archivo de log no existe"
  },
  "settings": {
    "name": "Nombre",
    "value": "Valor",
    "description": "Descripción",
    "setting_singular": "Parametro",
    "setting_plural": "Parametros"
  },
  "__": {
    "by": "por",
    "mys": "mis",
    "all": "Todo",
    "dynamic": "Dinamico",
    "classic": "Clasico",
    "public": "Público",
    "private": "Privado",
    "reserved zones": ":zones reservadas",
    "zone": "Zona",
    "no specified": "No Especificado",
    "of": "de",
    "party": "Fiesta",
    "reunion": "Reunión",
    "meeting": "Encuentro",
    "expose": "Exposición",
    "wedding": "Boda",
    "birthday": "Cumpleaños",
    "funeral": "Funeral",
    "date start": "Fecha inicio",
    "date end": "Fecha Fin",
    "Choose your option": "Escoge una opción",
    "update residences": "Actualizar Residencias",
    "view users": "Ver Usuarios",
    "relationship": "parentesco",
    "relationship_large": "parentesco con el propietario",
    "Residences with more Debt": "Con mas Deuda",
    "unpaid": "no pagado",
    "paid": "pagado",
    "partially paid": "parcialmente pagado",
    "cancelled": "cancelado",
    "no charge": "no cargado",
    "overdue": "atrasado",
    "fully refunded": "Reembolsado",
    "partially refunded": "parcialmente reembolsado",
    "waiting for approval": "esperando aprobación",
    "solvent": "Al día",
    "defaulter": "Moroso",
    "residence": "Residencia",
    "rent": "renta",
    "cash": "Efectivo",
    "check": "Cheque",
    "debit card": "Tarjeta de Débito",
    "credit card": "Tarjeta de Crédito",
    "deposit": "Deposito",
    "transfer": "Transferencia",
    "percentual": "Porcentual",
    "residential": "Residencial",
    "unique": "Único",
    "available": "Disponible",
    "occuped": "Ocupado",
    "parking": "Parqueadero",
    "set departure": "Marcar como ido",
    "approve": "aprobar",
    "reject": "rechazar",
    "success": "Éxito",
    "updated_successfully": "Actualizado Correctamente",
    "from": "De",
    "created_at": "Creado el",
    "updated_at": "Actualizado el",
    "deleted_at": "Eliminado el",
    "createds": "Creados",
    "go to": "Ir a",
    "open in maps": "Abrir en Mapas",
    "total charge": "Total en Gasto",
    "you have a new visit": "Tienes una visita",
    "advanced visit": "Visita Avanzada",
    "last visit": "Ultima :visit",
    "my visitors": "Mis :visitors",
    "my vehicles": "Mis :vehicles",
    "my workers": "Mis :workers",
    "my parkings": "Mis :parkings",
    "method": "Metodo",
    "report payment": "reportar pago",
    "send by mail": "enviar por correo",
    "print as pdf": "imprimir en pdf",
    "print options": "Opciones de Impresión",
    "name of residence": "nombre de la residencia",
    "residence percent": "percentual de la residencia",
    "status of residence": "status de la residencia",
    "quantity of person": "cantidad de personas",
    "phone of residence": "telefono de la residencia",
    "name of the person": "Nombre de la persona",
    "document of the person": "documento de la persona",
    "phone of the person": "telefono de la persona",
    "email of the person": "correo electronico",
    "image of the person": "imagen de la persona",
    "name of comunity": "Nombre de la comunidad",
    "address of comunity": "Dirección de la comunidad",
    "phone of comunity": "telefono de la comunidad",
    "account": "cuenta",
    "number of document": "numero de documento",
    "Geo Latitude": "Geo Latitud",
    "Geo Longitude": "Geo Longitud",
    "center image": "imagen centrada",
    "left image": "imagen alineada a la izquierda",
    "right image": "imagen alineada a la derecha",
    "car": "Carro",
    "bike": "Moto",
    "van": "Camioneta",
    "bicycle": "bicicleta",
    "boat": "Lancha",
    "golf cart": "Carro de golf",
    "bus": "Bus",
    "ambulance": "Ambulancia",
    "name of the owner": "Nombre del dueño",
    "document of the owner": "documento del dueño",
    "phone of the owner": "telefono del dueño",
    "email of the owner": "correo electronico",
    "image of the owner": "imagen del dueño",
    "Bad Request": "Solicitud Incorrecta",
    "Unauthorized Action": "Acción no Autorizada",
    "Forbidden": "Prohibido",
    "Not Found": "Pagina No Encontrado",
    "Internal Server Error": "Error Interno del servidor",
    "Network Error": "Error de Red",
    "Unauthorized": "No Autorizado",
    "Go to homepage": "Ir a la Pagina Principal",
    "are you sure": "Estas Seguro?",
    "Are you sure you want to generate the invoices? this action will be delete all the previous invoices generated": "¿Estas seguro de que quiere generar las facturas?. Esta acción borrara la facturas de este tipo previamente generadas para este periodo",
    "visit confirmed": ":visit confirmada de :visitor",
    "hours to cancel reservation": "Horas para cancelar la reservación",
    "number invoices to declare disabled": "Numero de Facturas para declarar Desactivado",
    "next events": "Proximos Eventos",
    "processed": "Procesado",
    "and others": " y otros ",
    "Thanks": "Gracias",
    "forgot password": "¿Olvido su contraseña?",
    "recover": "Recuperar",
    "recover password": "Recuperar Contraseña",
    "hello": "Hola",
    "go in": "Entrar",
    "we assign to you a new password": "Hemos reestablecido tu contraseña",
    "unkown visitor": "Visitante desconocido",
    "you have a reservation": "tienes una reservación",
    "view user": "Ver usuario",
    "add users": "Agregar usuarios",
    "update users": "Actualizar usuarios",
    "delete users": "Eliminar usuarios",
    "view residences": "Ver residencias",
    "add residences": "Agregar residencias ",
    "delete residences": "Eliminar residencias",
    "view invoices": "Ver facturas",
    "add invoices": "Añadir facturas",
    "update invoices": "Actualizar facturas",
    "delete invoices": "Eliminar facturas",
    "view vehicles": "Ver vehiculos",
    "add vehicles": "Agregar vehiculos",
    "update vehicles": "Actualizar vehiculos",
    "delete vehicles": "Eliminar Vehiculos",
    "view workers": "Ver trabajadores",
    "add workers": "Agregar trabajadores",
    "update workers": "Actualizar trabajadores",
    "delete workers": "Eliminar trabajadores",
    "view visitors": "Ver visitantes",
    "add visitors": "Agregar visitantes",
    "update visitors": "Actualizar visitantes",
    "delete visitors": "Eliminar visitantes",
    "view parkings": "Ver parqueaderos",
    "add parkings": "Agregar parqueaderos",
    "update parkings": "Actualizar parqueaderos",
    "delete parkings": "Eliminar parqueaderos",
    "view pets": "Ver mascotas",
    "add pets": "Agregar mascotas",
    "update pets": "Actualizar mascotas",
    "delete pets": "Eliminar mascotas",
    "view sliders": "Ver portadas",
    "add sliders": "Agregar portadas",
    "update sliders": "Actualizar portadas",
    "delete sliders": "Eliminar portadas",
    "view reservations": "Ver reservaciones",
    "add reservations": "Agregar reservaciones",
    "update reservations": "Actualizar reservaciones",
    "delete reservations": "Eliminar reservaciones",
    "view directives": "Ver directivas",
    "add directives": "Agregar directivas",
    "update directives": "Actualizar directivas",
    "delete directives": "Eliminar directivas",
    "view zones": "Ver areas",
    "add zones": "Agregar areas",
    "update zones": "Actualizar areas",
    "delete zones": "Eliminar areas",
    "view events": "Ver eventos",
    "add events": "Agregar eventos",
    "update events": "Actualizar eventos",
    "delete events": "Eliminar eventos",
    "view documents": "Ver documentos",
    "add documents": "Agregar documentos",
    "update documents": "Actualizar documentos",
    "delete documents": "Eliminar documentos",
    "view posts": "Ver noticias",
    "add posts": "Agregar noticias",
    "update posts": "Actualizar noticias",
    "delete posts": "Eliminar noticias",
    "view tags": "Ver tags",
    "add tags": "Agregar tags",
    "update tags": "Actualizar tags",
    "delete tags": "Eliminar tags",
    "view groups": "Ver grupos de residencias",
    "add groups": "Agregar grupos de residencias",
    "update groups": "Actualizar grupos de residencias",
    "delete groups": "Eliminar grupos de residencias",
    "view surveys": "Ver encuestas",
    "add surveys": "Agregar encuestas",
    "update surveys": "Actualizar encuestas",
    "delete surveys": "Eliminar encuestas",
    "view tickets": "Ver PQRs",
    "add tickets": "Agregar PQRs",
    "update tickets": "Actualizar PQRs",
    "delete tickets": "Eliminar PQRs",
    "view products": "Ver productos",
    "add products": "Agregar productos",
    "update products": "Actualizar productos",
    "delete products": "Eliminar productos",
    "view schedules": "Ver horarios",
    "add schedules": "Agregar horarios",
    "update schedules": "Actualizar horarios",
    "delete schedules": "Eliminar horarios",
    "view correspondences": "Ver correspondencias",
    "add correspondences": "Agregar correspondencias",
    "update correspondences": "Actualizar correspondencias",
    "delete correspondences": "Eliminar correspondencias",
    "view charges": "Ver cargos",
    "add charges": "Agregar cargos",
    "update charges": "Actualizar cargos",
    "delete charges": "Eliminar cargos",
    "view expenses": "Ver gastos",
    "add expenses": "Agregar gastos",
    "update expenses": "Actualizar gastos",
    "delete expenses": "Eliminar gastos",
    "Manage users": "Administrar usuarios",
    "Manage residences": "Administrar residencias",
    "Manage groups": "Administrar grupos de residencias",
    "Manage invoices": " Administrar facturas",
    "Manage vehicles": " Administrar vehiculos",
    "Manage workers": " Administrar trabajadores",
    "Manage visitors": " Administrar visitantes",
    "Manage parkings": "Administrar parqueaderos",
    "Manage pets": "Administrar mascotas",
    "Manage sliders": "Administrar portadas",
    "Manage reservations": "Administrar reservaciones",
    "Manage directives": "Administrar directiva",
    "Manage zones": "Administrar areas",
    "Manage events": "Administrar eventos",
    "Manage documents": "Administrar documentos",
    "Manage surveys": "Administrar encuestas",
    "Manage posts": "Administrar noticias",
    "Manage tags": "Administrar tags",
    "Manage tickets": "Administrar tickets",
    "Manage products": "Administrar productos",
    "Manage schedules": "Administrar horarios",
    "Manage panic logs": "Administrar historial de emergencias",
    "Manage correspondences": "Administrar correspondencias",
    "Manage expenses": "Administrar gastos",
    "Manage charges": "Administrar cargos",
    "Manage receipts": "Administrar recibos",
    "Finance": "Finanzista",
    "Celator": "Celador",
    "Accounter": "Contador",
    "Reports": "Reportes",
    "days discount invoices": "Dias en que la factura tendra descuento",
    "percent discount invoices": "Porcentaje de descuento por pago anticipado",
    "days interest invoices": "Dias que deben cumplirse para el  interes por mora en facturas",
    "percent interest invoices": "Porcentaje de interes por mora",
    "reserve fund": "Fondo de Reserva",
    "Summary Usage": "Resumen de Uso",
    "summary": "Resumen"
  }
}
